recipe: "regression/v1"
target_col: "fare_amount"
primary_metric: "root_mean_squared_error"
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    # Train/validation/test split ratios
    split_ratios: {{SPLIT_RATIOS|default([0.75, 0.125, 0.125])}}
    # Specifies the method to use to perform additional cleaning on split datasets
    # Note that arbitrary transformations should go into the transform step
    post_split_filter_method: create_dataset_filter
  transform:
    using: custom
    # Specifies the method that defines the data transformations to apply during model inference
    transformer_method: transformer_fn
  train:
    using: custom
    # Specifies the method that defines the estimator type and parameters to use for model training
    estimator_method: estimator_fn
  evaluate:
    # Sets performance thresholds that a trained model must meet in order to be eligible for
    # registration to the MLflow Model Registry
    validation_criteria:
      - metric: root_mean_squared_error
        threshold: 10
      - metric: mean_absolute_error
        threshold: 50
      - metric: weighted_mean_squared_error
        threshold: 50
  register:
    # Indicates whether or not a model that fails to meet performance thresholds should still
    # be registered to the MLflow Model Registry
    allow_non_validated_model: false
  ingest_scoring: {{INGEST_SCORING_CONFIG}}
  predict:
    output: {{PREDICT_OUTPUT_CONFIG}}
    # model_uri: "models/model.pkl"

# Defines custom performance metrics to compute during model training and evaluation
custom_metrics:
  - name: weighted_mean_squared_error
    # Specifies the name of the function in `steps/custom_metrics.py` to use to compute the metric
    function: weighted_mean_squared_error
    greater_is_better: False
